repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
        - id: check-yaml
          args: [ --allow-multiple-documents ]
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-added-large-files
        - id: check-merge-conflict
        - id: check-toml
        - id: check-xml
        - id: detect-private-key
        - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2  # Use the latest version available
    hooks:
      - id: mypy
        args: ["--strict", --ignore-missing-imports]  # Use strict mode to enforce type checking
        additional_dependencies:
          - "pydantic>=2.7.0"
          - "fastapi>=0.110.2"
          - "pytz>=2024.1"
          - "types-pytz>=2024.1"

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
